# 6.1 Future results for rf_var and mf_var
# ==============================================================================
# Generates future results only for the two corrected climate methods:
#   rf_var
#   mf_var
#
# Inputs:
#   result maps/rf_var/
#   result maps/mf_var/
#   assigned-zone filenames with future novel threshold 0.3
#
# Outputs:
#   1. Future ecosystem area by zone.
#   2. Normal-to-future ecosystem transition area.
#   3. Future population niche rasters.
#   4. Future species niche rasters.
#   5. Population- and species-level future suitable area tables.
#
# No figures are produced here. Figures are generated by script 11.1.
#
# New outputs are written to:
#   H:/Jing/ecoChina2/future tree niche var
#
# Existing script 6 outputs are not overwritten.
# ==============================================================================

library(terra)
library(data.table)

rm(list = ls())
gc()


# 0. Paths and settings ==========================================================

base_dir <- "H:/Jing/ecoChina2"

result_map_root <- file.path(
  base_dir,
  "result maps"
)

population_file <- file.path(
  base_dir,
  "species_zone_population_long.csv"
)

palette_file <- file.path(
  base_dir,
  "color_palette_China.csv"
)

reference_file <- file.path(
  base_dir,
  "raster/ecosys_ori.tif"
)

output_root <- file.path(
  base_dir,
  "future tree niche var"
)

table_dir <- file.path(
  output_root,
  "tables"
)

dir.create(
  output_root,
  recursive = TRUE,
  showWarnings = FALSE
)

dir.create(
  table_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

method_order <- c(
  "rf_var",
  "mf_var"
)

future_order <- c(
  "2011-2040SSP245",
  "2041-2070SSP245",
  "2071-2100SSP245",
  "2011-2040SSP585",
  "2041-2070SSP585",
  "2071-2100SSP585"
)

model_zoneID <- c(
  1:7,
  9:50,
  52:55
)

novel_threshold <- 0.4
tie_tol <- 1e-4
novel_value <- 99

reuse_existing_outputs <- TRUE


# 1. Helpers ====================================================================

assigned_map_file <- function(
    method,
    scenario) {
  
  file.path(
    result_map_root,
    method,
    paste0(
      "assigned_zone_",
      scenario,
      "_threshold",
      novel_threshold,
      "_tol",
      tie_tol,
      "_novel",
      novel_value,
      "_maskNA8_noNovelNormal.tif"
    )
  )
}


raster_is_valid <- function(
    raster_file,
    template) {
  
  if (!file.exists(raster_file)) {
    return(FALSE)
  }
  
  tryCatch({
    
    x <- rast(raster_file)
    
    compareGeom(
      x,
      template,
      stopOnError = FALSE
    )
    
  }, error = function(e) {
    FALSE
  })
}


scenario_fields <- function(
    scenario) {
  
  data.table(
    period = sub(
      "SSP.*$",
      "",
      scenario
    ),
    ssp = sub(
      "^.*(SSP[0-9]+)$",
      "\\1",
      scenario
    )
  )
}


# 2. Read population and palette data ===========================================

if (!file.exists(population_file)) {
  stop(
    "Missing population table: ",
    population_file
  )
}

if (!file.exists(palette_file)) {
  stop(
    "Missing palette table: ",
    palette_file
  )
}

if (!file.exists(reference_file)) {
  stop(
    "Missing reference raster: ",
    reference_file
  )
}

population <- fread(
  population_file
)

required_population_columns <- c(
  "PopulationID",
  "Species",
  "Zone",
  "Population"
)

if (!all(
  required_population_columns %in%
  names(population)
)) {
  stop(
    "Population table must contain: ",
    paste(
      required_population_columns,
      collapse = ", "
    )
  )
}

population[
  ,
  `:=`(
    PopulationID = as.character(
      PopulationID
    ),
    Species = as.character(
      Species
    ),
    Zone = as.character(
      Zone
    ),
    source_zone = as.integer(
      sub(
        "^Zone",
        "",
        Zone
      )
    ),
    reference_abundance = as.numeric(
      Population
    )
  )
]

if (anyNA(
  population$source_zone
)) {
  stop(
    "Some population zones could not be converted to numeric zone IDs."
  )
}

if (anyDuplicated(
  population[
    ,
    .(
      Species,
      source_zone
    )
  ]
)) {
  stop(
    "Duplicated species x source-zone populations were found."
  )
}

palette <- fread(
  palette_file
)

if (!all(
  c(
    "zoneID",
    "zone",
    "COLOR"
  ) %in% names(palette)
)) {
  stop(
    "Palette must contain zoneID, zone and COLOR columns."
  )
}

palette[
  ,
  zoneID := as.integer(zoneID)
]

population <- merge(
  population,
  palette[
    ,
    .(
      source_zone = zoneID,
      zone_name = zone,
      COLOR
    )
  ],
  by = "source_zone",
  all.x = TRUE,
  sort = FALSE
)

if (anyNA(
  population$COLOR
)) {
  stop(
    "Missing population colors for zones: ",
    paste(
      unique(
        population[
          is.na(COLOR),
          source_zone
        ]
      ),
      collapse = ", "
    )
  )
}

population[
  ,
  projected :=
    source_zone %in% model_zoneID
]

projected_population <- population[
  projected == TRUE
]

if (!nrow(
  projected_population
)) {
  stop(
    "No populations occur in modeled ecosystem zones."
  )
}

species_names <- sort(
  unique(
    projected_population$Species
  )
)

fwrite(
  population,
  file.path(
    table_dir,
    "population_projection_lookup_var.csv"
  )
)

fwrite(
  population[
    projected == FALSE
  ],
  file.path(
    table_dir,
    "population_projection_exclusions_var.csv"
  )
)


# 3. Find available assigned-zone maps ==========================================

normal_jobs <- data.table(
  method = method_order
)

normal_jobs[
  ,
  map_file := vapply(
    method,
    function(x) {
      assigned_map_file(
        x,
        "normal"
      )
    },
    character(1)
  )
]

missing_normal <- normal_jobs[
  !file.exists(map_file)
]

if (nrow(missing_normal) > 0) {
  stop(
    "Missing corrected normal assigned maps:\n",
    paste(
      paste0(
        missing_normal$method,
        " | ",
        missing_normal$map_file
      ),
      collapse = "\n"
    )
  )
}

future_jobs <- CJ(
  method = method_order,
  scenario = future_order,
  sorted = FALSE
)

future_jobs[
  ,
  map_file := mapply(
    assigned_map_file,
    method,
    scenario,
    USE.NAMES = FALSE
  )
]

available_jobs <- future_jobs[
  file.exists(map_file)
]

missing_jobs <- future_jobs[
  !file.exists(map_file)
]

fwrite(
  available_jobs,
  file.path(
    table_dir,
    "future_assigned_map_jobs_available_var.csv"
  )
)

fwrite(
  missing_jobs,
  file.path(
    table_dir,
    "future_assigned_map_jobs_missing_var.csv"
  )
)

if (nrow(missing_jobs) > 0) {
  
  cat(
    "\n[SKIP MISSING FUTURE MAPS]\n",
    paste(
      paste0(
        missing_jobs$method,
        " | ",
        missing_jobs$scenario,
        " | ",
        missing_jobs$map_file
      ),
      collapse = "\n"
    ),
    "\n",
    sep = ""
  )
}

if (!nrow(
  available_jobs
)) {
  stop(
    "No corrected future assigned-zone maps are available."
  )
}

jobs <- available_jobs

reference_map <- rast(
  reference_file
)

names(reference_map) <- "reference_zone"


# 4. Generate ecosystem, population and species results =========================

ecosystem_area_results <- list()
transition_results <- list()
population_area_results <- list()
species_area_results <- list()

ecosystem_index <- 0L
transition_index <- 0L
population_index <- 0L
species_index <- 0L

for (method_key in method_order) {
  
  normal_file <- assigned_map_file(
    method_key,
    "normal"
  )
  
  normal_map <- rast(
    normal_file
  )
  
  names(normal_map) <- "normal_zone"
  
  if (!compareGeom(
    normal_map,
    reference_map,
    stopOnError = FALSE
  )) {
    stop(
      "Normal-map geometry mismatch: ",
      normal_file
    )
  }
  
  method_jobs <- jobs[
    jobs[["method"]] == method_key
  ]
  
  for (job_index in seq_len(
    nrow(method_jobs)
  )) {
    
    scenario <- method_jobs$scenario[
      job_index
    ]
    
    map_file <- method_jobs$map_file[
      job_index
    ]
    
    cat(
      "\n==============================\n",
      "FUTURE RESULTS: ",
      method_key,
      " | ",
      scenario,
      "\n",
      "==============================\n",
      sep = ""
    )
    
    fields <- scenario_fields(
      scenario
    )
    
    future_map <- rast(
      map_file
    )
    
    names(future_map) <- "future_zone"
    
    if (!compareGeom(
      future_map,
      reference_map,
      stopOnError = FALSE
    )) {
      stop(
        "Future-map geometry mismatch: ",
        map_file
      )
    }
    
    cell_area <- cellSize(
      future_map,
      unit = "km"
    )
    
    
    # 4.1 Future ecosystem area by assigned zone --------------------------------
    
    ecosystem_area <- zonal(
      cell_area,
      future_map,
      fun = "sum",
      na.rm = TRUE
    )
    
    if (nrow(ecosystem_area) > 0) {
      
      names(ecosystem_area) <- c(
        "zoneID",
        "area_km2"
      )
      
      ecosystem_area <- as.data.table(
        ecosystem_area
      )
      
      ecosystem_area[
        ,
        `:=`(
          zoneID = as.integer(zoneID),
          method = method_key,
          scenario = scenario,
          period = fields$period,
          ssp = fields$ssp
        )
      ]
      
      ecosystem_area <- merge(
        ecosystem_area,
        palette,
        by = "zoneID",
        all.x = TRUE,
        sort = FALSE
      )
      
      ecosystem_index <- ecosystem_index + 1L
      
      ecosystem_area_results[[ecosystem_index]] <- ecosystem_area
    }
    
    
    # 4.2 Normal-to-future ecosystem transitions --------------------------------
    
    transition_code <- ifel(
      !is.na(normal_map) &
        !is.na(future_map),
      normal_map * 1000 +
        future_map,
      NA
    )
    
    transition_area <- zonal(
      cell_area,
      transition_code,
      fun = "sum",
      na.rm = TRUE
    )
    
    if (nrow(transition_area) > 0) {
      
      names(transition_area) <- c(
        "transition_code",
        "area_km2"
      )
      
      transition_area <- as.data.table(
        transition_area
      )
      
      transition_area[
        ,
        `:=`(
          normal_zone = as.integer(
            floor(
              transition_code / 1000
            )
          ),
          future_zone = as.integer(
            transition_code %% 1000
          ),
          method = method_key,
          scenario = scenario,
          period = fields$period,
          ssp = fields$ssp
        )
      ]
      
      transition_area[
        ,
        transition_type := fifelse(
          future_zone == novel_value,
          "novel",
          fifelse(
            normal_zone == future_zone,
            "stable",
            "changed"
          )
        )
      ]
      
      transition_index <- transition_index + 1L
      
      transition_results[[transition_index]] <- transition_area
    }
    
    
    # 4.3 Future population and species niches ----------------------------------
    
    population_dir <- file.path(
      output_root,
      method_key,
      scenario,
      "population niche"
    )
    
    species_dir <- file.path(
      output_root,
      method_key,
      scenario,
      "species niche"
    )
    
    dir.create(
      population_dir,
      recursive = TRUE,
      showWarnings = FALSE
    )
    
    dir.create(
      species_dir,
      recursive = TRUE,
      showWarnings = FALSE
    )
    
    for (species_name in species_names) {
      
      species_population <- projected_population[
        Species == species_name
      ][order(source_zone)]
      
      population_zones <- species_population$source_zone
      
      population_output <- file.path(
        population_dir,
        paste0(
          species_name,
          "_population_niche.tif"
        )
      )
      
      species_output <- file.path(
        species_dir,
        paste0(
          species_name,
          "_species_niche.tif"
        )
      )
      
      reuse_output <- (
        reuse_existing_outputs &&
          raster_is_valid(
            population_output,
            future_map
          ) &&
          raster_is_valid(
            species_output,
            future_map
          )
      )
      
      if (reuse_output) {
        
        population_map <- rast(
          population_output
        )
        
        species_map <- rast(
          species_output
        )
        
        names(population_map) <-
          "source_zone"
        
        names(species_map) <-
          "species_suitable"
        
        cat(
          "[REUSE]",
          species_name,
          "\n"
        )
        
      } else {
        
        population_map <- subst(
          future_map,
          from = population_zones,
          to = population_zones,
          others = NA
        )
        
        names(population_map) <-
          "source_zone"
        
        writeRaster(
          population_map,
          population_output,
          overwrite = TRUE,
          wopt = list(
            datatype = "INT2S",
            gdal = "COMPRESS=LZW"
          )
        )
        
        species_map <- ifel(
          !is.na(population_map),
          1,
          NA
        )
        
        names(species_map) <-
          "species_suitable"
        
        writeRaster(
          species_map,
          species_output,
          overwrite = TRUE,
          wopt = list(
            datatype = "INT1U",
            gdal = "COMPRESS=LZW"
          )
        )
      }
      
      population_area <- zonal(
        cell_area,
        population_map,
        fun = "sum",
        na.rm = TRUE
      )
      
      if (nrow(population_area) > 0) {
        
        names(population_area) <- c(
          "source_zone",
          "future_area_km2"
        )
        
        population_area <- as.data.table(
          population_area
        )
        
        population_area <- merge(
          species_population[
            ,
            .(
              PopulationID,
              Species,
              source_zone,
              zone_name,
              COLOR,
              reference_abundance
            )
          ],
          population_area,
          by = "source_zone",
          all.x = TRUE,
          sort = FALSE
        )
        
      } else {
        
        population_area <- species_population[
          ,
          .(
            PopulationID,
            Species,
            source_zone,
            zone_name,
            COLOR,
            reference_abundance,
            future_area_km2 = 0
          )
        ]
      }
      
      population_area[
        is.na(future_area_km2),
        future_area_km2 := 0
      ]
      
      population_area[
        ,
        `:=`(
          method = method_key,
          scenario = scenario,
          period = fields$period,
          ssp = fields$ssp,
          population_raster =
            population_output
        )
      ]
      
      population_index <- population_index + 1L
      
      population_area_results[[population_index]] <- population_area
      
      species_area_km2 <- global(
        cell_area * species_map,
        fun = "sum",
        na.rm = TRUE
      )[1, 1]
      
      species_index <- species_index + 1L
      
      species_area_results[[species_index]] <- data.table(
        Species = species_name,
        method = method_key,
        scenario = scenario,
        period = fields$period,
        ssp = fields$ssp,
        populations_projected =
          length(population_zones),
        future_area_km2 =
          species_area_km2,
        species_raster =
          species_output
      )
      
      cat(
        "[SAVED]",
        species_name,
        "| area km2:",
        round(
          species_area_km2,
          2
        ),
        "\n"
      )
      
      rm(
        population_map,
        species_map,
        population_area
      )
      
      gc()
    }
    
    rm(
      future_map,
      cell_area,
      transition_code
    )
    
    gc()
  }
  
  rm(normal_map)
  gc()
}


# 5. Save result tables ==========================================================

ecosystem_area_table <- rbindlist(
  ecosystem_area_results,
  fill = TRUE
)

transition_table <- rbindlist(
  transition_results,
  fill = TRUE
)

population_area_table <- rbindlist(
  population_area_results,
  fill = TRUE
)

species_area_table <- rbindlist(
  species_area_results,
  fill = TRUE
)

setorder(
  ecosystem_area_table,
  method,
  ssp,
  period,
  zoneID
)

setorder(
  transition_table,
  method,
  ssp,
  period,
  normal_zone,
  future_zone
)

setorder(
  population_area_table,
  Species,
  source_zone,
  method,
  ssp,
  period
)

setorder(
  species_area_table,
  Species,
  method,
  ssp,
  period
)

fwrite(
  ecosystem_area_table,
  file.path(
    table_dir,
    "future_ecosystem_area_var.csv"
  )
)

fwrite(
  transition_table,
  file.path(
    table_dir,
    "future_ecosystem_transition_var.csv"
  )
)

fwrite(
  population_area_table,
  file.path(
    table_dir,
    "future_population_niche_area_var.csv"
  )
)

fwrite(
  species_area_table,
  file.path(
    table_dir,
    "future_species_niche_area_var.csv"
  )
)

cat(
  "\nCOMPLETE\n",
  "Methods: ",
  paste(
    method_order,
    collapse = ", "
  ),
  "\n",
  "Future novel threshold: ",
  novel_threshold,
  "\n",
  "Available future jobs processed: ",
  nrow(jobs),
  "\n",
  "Output root: ",
  output_root,
  "\n",
  sep = ""
)
