# 6.2 Future population and species niches from dual suitability
# ==============================================================
# Definition:
#   Population niche = dual suitability raster of its source ecotype zone.
#   Species niche    = pixel-wise maximum of all population dual suitability rasters.
#
# Extra output:
#   For each species x method x scenario, record per-pixel population ranking:
#     rank1_zone, rank2_zone, ...
#     rank1_suit, rank2_suit, ...
#
# This script does NOT regenerate outputs from script 6.
# It reads the population lookup generated by script 6:
#   future tree niche/tables/population_projection_lookup.csv
#
# New outputs are saved under:
#   future tree niche dual suitability/

library(terra)
library(data.table)

rm(list = ls())
gc()

# 0. Paths and settings ==========================================================

base_dir <- "H:/Jing/ecoChina2"

dual_root <- file.path(base_dir, "dual suit")

code6_table_dir <- file.path(base_dir, "future tree niche", "tables")
pop_lookup_file <- file.path(code6_table_dir, "population_projection_lookup.csv")

reference_file <- file.path(base_dir, "raster/ecosys_ori.tif")

output_root <- file.path(base_dir, "future tree niche dual suitability")
table_dir <- file.path(output_root, "tables")

tmp_dir <- file.path(base_dir, "tmp_dual_population_niche")

dir.create(output_root, recursive = TRUE, showWarnings = FALSE)
dir.create(table_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(tmp_dir, recursive = TRUE, showWarnings = FALSE)

terraOptions(tempdir = tmp_dir, memfrac = 0.15)

method_order <- c(
  "optimized_mf",
  "optimized_rf",
  "plain_mf",
  "plain_rf"
)

future_order <- c(
  "2011-2040SSP245",
  "2041-2070SSP245",
  "2071-2100SSP245",
  "2011-2040SSP585",
  "2041-2070SSP585",
  "2071-2100SSP585"
)

model_zoneID <- c(1:7, 9:50, 52:55)

# Used to summarize binary suitable area.
suitability_threshold <- 0.2

# Used only for ranking. Values <= this are not ranked.
# Keep as 0 to record all positive dual suitability overlaps.
rank_min_suitability <- 0

# Reuse outputs from this new 6.2 folder on reruns.
reuse_existing_outputs <- TRUE

# Usually FALSE to avoid duplicating huge population rasters.
# Population niche is already exactly the source-zone dual raster.
write_population_stack <- FALSE

# 1. Helper functions ===========================================================

safe_name <- function(x) {
  x <- gsub("[^A-Za-z0-9_]+", "_", x)
  x <- gsub("^_+|_+$", "", x)
  ifelse(nchar(x) == 0, "unnamed", x)
}

remove_raster_files <- function(filepath) {
  base <- tools::file_path_sans_ext(filepath)
  
  files <- unique(c(
    filepath,
    paste0(filepath, ".aux.xml"),
    paste0(filepath, ".ovr"),
    paste0(filepath, ".msk"),
    paste0(base, ".aux.xml"),
    paste0(base, ".ovr"),
    paste0(base, ".tfw")
  ))
  
  files <- files[file.exists(files)]
  
  if (length(files) > 0) {
    gc()
    suppressWarnings(unlink(files, force = TRUE))
  }
  
  invisible(TRUE)
}

dual_file <- function(method, scenario, zone) {
  file.path(
    dual_root,
    method,
    scenario,
    paste0("dual_suitability_zone", zone, ".tif")
  )
}

global_scalar <- function(r, fun, zero_if_missing = FALSE) {
  v <- tryCatch(
    global(r, fun = fun, na.rm = TRUE)[1, 1],
    error = function(e) NA_real_
  )
  
  v <- as.numeric(v)
  
  if (length(v) == 0 || !is.finite(v)) {
    if (zero_if_missing) return(0)
    return(NA_real_)
  }
  
  v
}

suitable_area <- function(suit, cell_area, threshold) {
  a <- ifel(
    !is.na(suit) & suit > threshold,
    cell_area,
    NA
  )
  
  global_scalar(a, "sum", zero_if_missing = TRUE)
}

weighted_area <- function(suit, cell_area) {
  global_scalar(suit * cell_area, "sum", zero_if_missing = TRUE)
}

mean_suitability <- function(suit) {
  global_scalar(suit, "mean", zero_if_missing = FALSE)
}

max_suitability <- function(suit) {
  global_scalar(suit, "max", zero_if_missing = FALSE)
}

max_stack_na <- function(x) {
  if (all(is.na(x))) return(NA_real_)
  max(x, na.rm = TRUE)
}

rank_layer_names <- function(k, prefix) {
  paste0("rank", seq_len(k), "_", prefix)
}

rank_dual_cell <- function(x, pop_zones, rank_min, suit_threshold) {
  k <- length(pop_zones)
  
  out_zone <- rep(NA_real_, k)
  out_suit <- rep(NA_real_, k)
  
  valid_rank <- which(
    !is.na(x) &
      is.finite(x) &
      x > rank_min
  )
  
  valid_suit <- which(
    !is.na(x) &
      is.finite(x) &
      x > suit_threshold
  )
  
  if (length(valid_rank) > 0) {
    # Higher dual suitability first.
    # Exact ties are ordered by smaller source zone for reproducibility.
    ord <- valid_rank[order(-x[valid_rank], pop_zones[valid_rank])]
    
    out_zone[seq_along(ord)] <- pop_zones[ord]
    out_suit[seq_along(ord)] <- x[ord]
  }
  
  top1_minus_top2 <- NA_real_
  
  if (length(valid_rank) >= 2) {
    top1_minus_top2 <- out_suit[1] - out_suit[2]
  }
  
  c(
    out_zone,
    out_suit,
    n_pop_ranked = length(valid_rank),
    n_pop_suitable = length(valid_suit),
    top1_minus_top2 = top1_minus_top2
  )
}

read_dual_stack <- function(files, layer_names, template) {
  s <- rast(files)
  names(s) <- layer_names
  
  if (!compareGeom(s, template, stopOnError = FALSE)) {
    cat("[RESAMPLE] dual rasters to reference geometry\n")
    s <- resample(s, template, method = "bilinear")
    names(s) <- layer_names
  }
  
  s <- mask(s, template)
  names(s) <- layer_names
  
  s
}

# 2. Read population lookup generated by script 6 ===============================

if (!file.exists(pop_lookup_file)) {
  stop(
    "Missing population lookup from script 6:\n",
    pop_lookup_file,
    "\nRun script 6 first, or check the file path."
  )
}

if (!file.exists(reference_file)) {
  stop("Missing reference raster: ", reference_file)
}

pop <- fread(pop_lookup_file)

required_cols <- c(
  "PopulationID",
  "Species",
  "source_zone"
)

if (!all(required_cols %in% names(pop))) {
  stop(
    "population_projection_lookup.csv must contain: ",
    paste(required_cols, collapse = ", ")
  )
}

pop[, `:=`(
  PopulationID = as.character(PopulationID),
  Species = as.character(Species),
  source_zone = as.integer(source_zone)
)]

if (!"projected" %in% names(pop)) {
  pop[, projected := source_zone %in% model_zoneID]
} else {
  pop[, projected := as.logical(projected)]
}

if (!"reference_abundance" %in% names(pop)) {
  if ("Population" %in% names(pop)) {
    pop[, reference_abundance := as.numeric(Population)]
  } else {
    pop[, reference_abundance := NA_real_]
  }
}

if (!"zone_name" %in% names(pop)) {
  pop[, zone_name := NA_character_]
}

if (!"COLOR" %in% names(pop)) {
  pop[, COLOR := NA_character_]
}

# Same population definition as script 6:
# one species x source-zone combination = one population.
if (anyDuplicated(pop[, .(Species, source_zone)])) {
  stop("Duplicated species x source-zone populations were found.")
}

projected_pop <- pop[
  projected == TRUE &
    source_zone %in% model_zoneID
]

if (!nrow(projected_pop)) {
  stop("No projected populations remain after excluding unmodelled zones.")
}

required_zones <- sort(unique(projected_pop$source_zone))
species_names <- sort(unique(projected_pop$Species))

fwrite(
  projected_pop,
  file.path(table_dir, "dual_population_projection_lookup_from_code6.csv")
)

fwrite(
  pop[projected == FALSE | !(source_zone %in% model_zoneID)],
  file.path(table_dir, "dual_population_projection_exclusions.csv")
)

cat(
  "\n[POPULATION LOOKUP]\n",
  "Species: ", length(species_names), "\n",
  "Projected populations: ", nrow(projected_pop), "\n",
  "Required source zones: ", paste(required_zones, collapse = ", "), "\n",
  sep = ""
)

# 3. Find available dual suitability jobs =======================================

job_list <- list()

for (method in method_order) {
  for (scenario in future_order) {
    
    files <- dual_file(method, scenario, required_zones)
    missing_zones <- required_zones[!file.exists(files)]
    
    job_list[[length(job_list) + 1L]] <- data.table(
      method = method,
      scenario = scenario,
      n_required_zones = length(required_zones),
      n_missing_zones = length(missing_zones),
      missing_zones = paste(missing_zones, collapse = ",")
    )
  }
}

jobs <- rbindlist(job_list)

available_jobs <- jobs[n_missing_zones == 0]
missing_jobs <- jobs[n_missing_zones > 0]

fwrite(
  available_jobs,
  file.path(table_dir, "dual_suitability_jobs_available.csv")
)

fwrite(
  missing_jobs,
  file.path(table_dir, "dual_suitability_jobs_missing.csv")
)

if (nrow(available_jobs) == 0) {
  stop(
    "No complete dual suitability jobs found.\n",
    "Check: ",
    file.path(table_dir, "dual_suitability_jobs_missing.csv")
  )
}

cat(
  "\n[AVAILABLE DUAL SUITABILITY JOBS]\n",
  "Available jobs: ", nrow(available_jobs), " of ", nrow(jobs), "\n",
  sep = ""
)

print(available_jobs[, .(method, scenario)])

# 4. Prepare template and output containers =====================================

reference_map <- rast(reference_file)
names(reference_map) <- "zoneID"

cell_area <- cellSize(
  reference_map,
  unit = "km"
)

population_area_results <- list()
species_area_results <- list()
population_layer_index <- list()
species_raster_index <- list()
population_rank_index <- list()

# 5. Generate dual-based population and species niches ==========================

for (j in seq_len(nrow(available_jobs))) {
  
  method <- available_jobs$method[j]
  scenario <- available_jobs$scenario[j]
  
  cat(
    "\n==============================\n",
    "DUAL-BASED TREE NICHE: ",
    method,
    " | ",
    scenario,
    "\n",
    "==============================\n",
    sep = ""
  )
  
  population_dir <- file.path(
    output_root,
    method,
    scenario,
    "population niche"
  )
  
  species_dir <- file.path(
    output_root,
    method,
    scenario,
    "species niche"
  )
  
  species_binary_dir <- file.path(
    output_root,
    method,
    scenario,
    "species niche binary"
  )
  
  rank_dir <- file.path(
    output_root,
    method,
    scenario,
    "population ranking"
  )
  
  dir.create(population_dir, recursive = TRUE, showWarnings = FALSE)
  dir.create(species_dir, recursive = TRUE, showWarnings = FALSE)
  dir.create(species_binary_dir, recursive = TRUE, showWarnings = FALSE)
  dir.create(rank_dir, recursive = TRUE, showWarnings = FALSE)
  
  for (species_name in species_names) {
    
    species_pop <- projected_pop[
      Species == species_name
    ][order(source_zone)]
    
    pop_zones <- species_pop$source_zone
    
    if (!length(pop_zones)) next
    
    safe_species <- safe_name(species_name)
    
    pop_files <- dual_file(
      method = method,
      scenario = scenario,
      zone = pop_zones
    )
    
    if (!all(file.exists(pop_files))) {
      cat("[SKIP SPECIES] missing dual raster:", species_name, "\n")
      next
    }
    
    layer_names <- make.unique(
      paste0("pop_zone", pop_zones)
    )
    
    population_stack_file <- file.path(
      population_dir,
      paste0(
        safe_species,
        "_population_dual_suitability.tif"
      )
    )
    
    species_file <- file.path(
      species_dir,
      paste0(
        safe_species,
        "_species_dual_suitability.tif"
      )
    )
    
    species_binary_file <- file.path(
      species_binary_dir,
      paste0(
        safe_species,
        "_species_dual_binary_threshold",
        suitability_threshold,
        ".tif"
      )
    )
    
    rank_zone_file <- file.path(
      rank_dir,
      paste0(
        safe_species,
        "_ranked_population_zones.tif"
      )
    )
    
    rank_suit_file <- file.path(
      rank_dir,
      paste0(
        safe_species,
        "_ranked_population_suitability.tif"
      )
    )
    
    rank_summary_file <- file.path(
      rank_dir,
      paste0(
        safe_species,
        "_ranked_population_summary.tif"
      )
    )
    
    rank_index_file <- file.path(
      rank_dir,
      paste0(
        safe_species,
        "_population_rank_index.csv"
      )
    )
    
    # Population niches are read directly from source-zone dual rasters.
    pop_stack <- read_dual_stack(
      files = pop_files,
      layer_names = layer_names,
      template = reference_map
    )
    
    # Optional duplicate output.
    # Normally unnecessary because each layer is exactly an existing dual raster.
    if (write_population_stack) {
      if (
        !reuse_existing_outputs ||
        !file.exists(population_stack_file)
      ) {
        remove_raster_files(population_stack_file)
        
        writeRaster(
          pop_stack,
          population_stack_file,
          overwrite = TRUE,
          wopt = list(
            datatype = "FLT4S",
            gdal = "COMPRESS=LZW"
          )
        )
      }
    }
    
    # 5.1 Species niche: max across population dual suitability layers ----------
    
    species_map <- NULL
    
    if (
      reuse_existing_outputs &&
      file.exists(species_file)
    ) {
      species_map0 <- rast(species_file)
      
      if (compareGeom(species_map0, reference_map, stopOnError = FALSE)) {
        species_map <- species_map0
        names(species_map) <- "species_dual_suitability"
        cat("[REUSE SPECIES]", species_name, "|", method, "|", scenario, "\n")
      } else {
        rm(species_map0)
        gc()
      }
    }
    
    if (is.null(species_map)) {
      if (nlyr(pop_stack) == 1) {
        species_map <- pop_stack[[1]]
      } else {
        species_map <- app(
          pop_stack,
          fun = max_stack_na
        )
      }
      
      names(species_map) <- "species_dual_suitability"
      
      remove_raster_files(species_file)
      
      writeRaster(
        species_map,
        species_file,
        overwrite = TRUE,
        wopt = list(
          datatype = "FLT4S",
          gdal = "COMPRESS=LZW"
        )
      )
    }
    
    # Binary species niche is for area summary and quick visualization.
    if (
      !reuse_existing_outputs ||
      !file.exists(species_binary_file)
    ) {
      species_binary <- ifel(
        !is.na(species_map) &
          species_map > suitability_threshold,
        1,
        NA
      )
      
      names(species_binary) <- "species_suitable"
      
      remove_raster_files(species_binary_file)
      
      writeRaster(
        species_binary,
        species_binary_file,
        overwrite = TRUE,
        wopt = list(
          datatype = "INT1U",
          gdal = "COMPRESS=LZW"
        )
      )
      
      rm(species_binary)
      gc()
    }
    
    # 5.2 Ranked population overlap record --------------------------------------
    # For each pixel, rank source-zone populations by dual suitability.
    # Output is paired raster stacks:
    #   ranked_population_zones.tif       rank1_zone, rank2_zone, ...
    #   ranked_population_suitability.tif rank1_suit, rank2_suit, ...
    
    reuse_rank <- (
      reuse_existing_outputs &&
        file.exists(rank_zone_file) &&
        file.exists(rank_suit_file) &&
        file.exists(rank_summary_file)
    )
    
    if (!reuse_rank) {
      
      rank_all <- app(
        pop_stack,
        fun = function(x) {
          rank_dual_cell(
            x = x,
            pop_zones = pop_zones,
            rank_min = rank_min_suitability,
            suit_threshold = suitability_threshold
          )
        }
      )
      
      k_pop <- length(pop_zones)
      
      zone_layers <- seq_len(k_pop)
      suit_layers <- k_pop + seq_len(k_pop)
      summary_layers <- 2 * k_pop + c(1, 2, 3)
      
      rank_zone <- rank_all[[zone_layers]]
      names(rank_zone) <- rank_layer_names(k_pop, "zone")
      
      rank_suit <- rank_all[[suit_layers]]
      names(rank_suit) <- rank_layer_names(k_pop, "suit")
      
      rank_summary <- rank_all[[summary_layers]]
      names(rank_summary) <- c(
        "n_pop_ranked",
        "n_pop_suitable",
        "top1_minus_top2"
      )
      
      remove_raster_files(rank_zone_file)
      remove_raster_files(rank_suit_file)
      remove_raster_files(rank_summary_file)
      
      writeRaster(
        rank_zone,
        rank_zone_file,
        overwrite = TRUE,
        wopt = list(
          datatype = "INT2S",
          gdal = "COMPRESS=LZW"
        )
      )
      
      writeRaster(
        rank_suit,
        rank_suit_file,
        overwrite = TRUE,
        wopt = list(
          datatype = "FLT4S",
          gdal = "COMPRESS=LZW"
        )
      )
      
      writeRaster(
        rank_summary,
        rank_summary_file,
        overwrite = TRUE,
        wopt = list(
          datatype = "FLT4S",
          gdal = "COMPRESS=LZW"
        )
      )
      
      rm(rank_all, rank_zone, rank_suit, rank_summary)
      gc()
    }
    
    rank_index <- data.table(
      Species = species_name,
      PopulationID = species_pop$PopulationID,
      source_zone = species_pop$source_zone,
      zone_name = species_pop$zone_name,
      method = method,
      scenario = scenario,
      original_layer_in_pop_stack = seq_along(pop_zones),
      rank_min_suitability = rank_min_suitability,
      dual_threshold = suitability_threshold,
      source_dual_raster = pop_files,
      ranked_zone_raster = rank_zone_file,
      ranked_suitability_raster = rank_suit_file,
      ranked_summary_raster = rank_summary_file
    )
    
    fwrite(
      rank_index,
      rank_index_file
    )
    
    population_rank_index[[length(population_rank_index) + 1L]] <- rank_index
    
    # 5.3 Population-level area summaries ---------------------------------------
    
    pop_area <- rbindlist(
      lapply(seq_along(pop_zones), function(k) {
        
        lyr <- pop_stack[[k]]
        
        data.table(
          Species = species_name,
          PopulationID = species_pop$PopulationID[k],
          source_zone = species_pop$source_zone[k],
          zone_name = species_pop$zone_name[k],
          reference_abundance = species_pop$reference_abundance[k],
          method = method,
          scenario = scenario,
          dual_threshold = suitability_threshold,
          rank_min_suitability = rank_min_suitability,
          
          suitable_area_km2 = suitable_area(
            lyr,
            cell_area,
            suitability_threshold
          ),
          
          suitability_weighted_area_km2 = weighted_area(
            lyr,
            cell_area
          ),
          
          mean_dual_suitability = mean_suitability(lyr),
          max_dual_suitability = max_suitability(lyr),
          
          population_niche_definition =
            "source-zone dual suitability raster",
          
          source_dual_raster = pop_files[k],
          
          population_stack_file = if (write_population_stack) {
            population_stack_file
          } else {
            NA_character_
          },
          
          layer = k,
          layer_name = layer_names[k],
          COLOR = species_pop$COLOR[k]
        )
      }),
      fill = TRUE
    )
    
    population_area_results[[length(population_area_results) + 1L]] <- pop_area
    
    # 5.4 Species-level area summary --------------------------------------------
    
    species_area_results[[length(species_area_results) + 1L]] <- data.table(
      Species = species_name,
      method = method,
      scenario = scenario,
      populations_projected = length(pop_zones),
      dual_threshold = suitability_threshold,
      rank_min_suitability = rank_min_suitability,
      
      suitable_area_km2 = suitable_area(
        species_map,
        cell_area,
        suitability_threshold
      ),
      
      suitability_weighted_area_km2 = weighted_area(
        species_map,
        cell_area
      ),
      
      mean_dual_suitability = mean_suitability(species_map),
      max_dual_suitability = max_suitability(species_map),
      
      species_niche_definition =
        "pixel-wise maximum of source population dual suitability rasters",
      
      species_raster = species_file,
      species_binary_raster = species_binary_file,
      ranked_zone_raster = rank_zone_file,
      ranked_suitability_raster = rank_suit_file,
      ranked_summary_raster = rank_summary_file
    )
    
    # 5.5 Layer index ------------------------------------------------------------
    
    population_layer_index[[length(population_layer_index) + 1L]] <- data.table(
      Species = species_name,
      PopulationID = species_pop$PopulationID,
      source_zone = species_pop$source_zone,
      zone_name = species_pop$zone_name,
      method = method,
      scenario = scenario,
      layer = seq_along(pop_zones),
      layer_name = layer_names,
      source_dual_raster = pop_files,
      population_stack_file = if (write_population_stack) {
        population_stack_file
      } else {
        NA_character_
      }
    )
    
    species_raster_index[[length(species_raster_index) + 1L]] <- data.table(
      Species = species_name,
      method = method,
      scenario = scenario,
      populations_projected = length(pop_zones),
      species_raster = species_file,
      species_binary_raster = species_binary_file,
      ranked_zone_raster = rank_zone_file,
      ranked_suitability_raster = rank_suit_file,
      ranked_summary_raster = rank_summary_file
    )
    
    cat(
      "[SAVED]",
      species_name,
      "| populations:",
      length(pop_zones),
      "| species suitable area km2:",
      round(
        species_area_results[[length(species_area_results)]]$suitable_area_km2,
        2
      ),
      "\n"
    )
    
    rm(pop_stack, species_map, pop_area, rank_index)
    gc()
  }
}

# 6. Save summary tables =========================================================

if (!length(population_area_results)) {
  stop("No population-level results were generated.")
}

population_area <- rbindlist(
  population_area_results,
  fill = TRUE
)

species_area <- rbindlist(
  species_area_results,
  fill = TRUE
)

population_layers <- rbindlist(
  population_layer_index,
  fill = TRUE
)

species_index <- rbindlist(
  species_raster_index,
  fill = TRUE
)

population_rank_index_all <- rbindlist(
  population_rank_index,
  fill = TRUE
)

setorder(
  population_area,
  Species,
  source_zone,
  method,
  scenario
)

setorder(
  species_area,
  Species,
  method,
  scenario
)

setorder(
  population_layers,
  Species,
  source_zone,
  method,
  scenario
)

setorder(
  species_index,
  Species,
  method,
  scenario
)

setorder(
  population_rank_index_all,
  Species,
  source_zone,
  method,
  scenario
)

fwrite(
  population_area,
  file.path(
    table_dir,
    "dual_population_niche_area.csv"
  )
)

fwrite(
  species_area,
  file.path(
    table_dir,
    "dual_species_niche_area.csv"
  )
)

fwrite(
  population_layers,
  file.path(
    table_dir,
    "dual_population_layer_index.csv"
  )
)

fwrite(
  species_index,
  file.path(
    table_dir,
    "dual_species_raster_index.csv"
  )
)

fwrite(
  population_rank_index_all,
  file.path(
    table_dir,
    "dual_population_rank_index.csv"
  )
)

cat(
  "\nCOMPLETE\n",
  "Output root: ",
  output_root,
  "\n",
  "Available dual jobs processed: ",
  nrow(available_jobs),
  " of ",
  nrow(jobs),
  "\n",
  "Species: ",
  length(species_names),
  "\n",
  "Population niche definition: source-zone dual suitability raster\n",
  "Species niche definition: pixel-wise max of population dual suitability rasters\n",
  "Population ranking: per-pixel ordered source-zone populations and dual suitability\n",
  "Population rasters duplicated: ",
  write_population_stack,
  "\n",
  sep = ""
)